### PR TITLE
Design Update, Mobile Functionality & Theme Improvement

### PR DESCRIPTION
**Pull request by aegrey**
**Update**
I updated the code based upon the content export to work with the existing content without any changes. For appearance changes, the H1s (#) should be changed to H2s (##) to look like the comp (serif font). Without this change, they'll just have the sans-serif font.   
   
As mentioned, I suggest we add this as a separate theme before merging the code so we can switch back and forth until such time everything is looking good to everyone.   
   

**Github Project:** Add, edit, or review tasks/issues and status of update here:    
**https://github.com/aegrey/Rosa/projects/1**

# Overview
This PR is a large overhaul of several parts of the site/theme. Normally I would make this several separate PRs, however this all works together and depends on one another. Two of the major categories addressed in this PR includes:
- **Optimization:** Large scale code clean-up, improvements, and build refactor, site/file architecture.
- **Design:** Full design update in relation to previously presented mock-ups & mobile design & functionality. 

## Optimization Details
- Refactoring the gulp file, removed postcss and simplified the build. Added JS & SASS builders, Lint,  and additional build task for a production build that minimizes files to improve load.
- Moved CSS to SASS to allow for more functionality options including nesting, variables, and mixins and better hierarchy so include files allow to easily separate and access styles for a specific area of the site. Cleaned up many styles in the current CSS code, but merged the remainder over in _old include files (*To be completed in future PR*).
- Moved Javascript to separate files to easily update, remove duplicate functionality, and allow for better future updates.
- Small changes to file structure including adding scss, js, and images folders.
- Added a editorconfig to improve code consistency.
- Updated the README to be more specific to the site and documented new gulp functionality.

## Design Details
- Global update to fonts used and title/copy sizing and style improvements. 
- Updated post/page/post card pages width to better utilize the space and general style improvements overall.
- Re-design of header to include logo, title, social icons, and navigation.
- Addition of sub-navigation for pages, currently with manual setup in themes (*future improvements needed, also not included in mobile at this time*).
- Creation of a sub-nav menu for the home page (*Needs changes in ghost content before functional*)
- Re-design of floating menu to include navigation and more relevant UX.
- Re-design of mobile view (and fixing so it's actually functional) including header, fixing several design/layout issues, and simplifying overall site CSS so site is somewhat mobile-first so less changes will be needed for responsive design.
- Added rose at the bottom of content per suggestion.

----

#### Future Planned Updates
- Adding a clean functionality to Gulp files to remove map files and clean builds to further minify files. 
- Complete CSS cleanup by cleaning up all old styles, removing un-needed styles, and combine & simplifying styles.
- Clean up Javascript for floating menu and improve functionality & smoothing, especially in IE. Further integrate separate global Javascript files to remove scripts from pages.
- Add sub-navigation to mobile navigation.

----

## Screenshots
Screenshots below illustrate current view state of the site at this point & expected visual experience on testing.

##### New Desktop Header/Homepage View
screen shot 2017-10-10 at 11 58 26 am

##### Desktop Floating Menu/Home Article List View
screen shot 2017-10-10 at 11 58 52 am

##### Desktop Tag View (News)
screen shot 2017-10-10 at 12 00 09 pm

##### Desktop Page/Post View
screen shot 2017-10-10 at 12 03 52 pm

##### Mobile Home View/Navigation
screen shot 2017-10-10 at 12 10 47 pm

#### Mobile Page/Post View
screen shot 2017-10-10 at 12 02 39 pm

### CODE REVIEW

**Comment by simonv3** [comment]
Awesome, thanks @aegrey, do you have a list of things we have to apply to the data before we can apply this to the site?

**Comment by aegrey** [comment]
@simonv3 Yep, I'm loading the JSON file now and will DM with updates.

**Comment by aegrey** [comment]
@simonv3 I just pushed a few updates based on the content so that the only thing that needs to be changed is the # to ##'s on the homepage, so it's good to go, when it's uploaded, it's a quick change and not required for functionality.

**Comment by simonv3** [comment]
@aegrey let me know when you want me to merge this in! We've switched over on the site so might as well make it official here ;)

(or feel free to merge it in yourself)

**Comment by aegrey** [comment]
@simonv3 Got some feedback, thus far everyone has been happy with it and no bugs reported, so I think a merge is great!

I'm not a member of the dsa-lsc group so I don't have merge permissions, so it's all you. :)

**Comment by simonv3** [comment]
@aegrey I just made you a contributor, sorry I didn't do that earlier!

Let's move that project over, or maybe move that stuff in the Trello? Either way works for me.

**Pull request merged**
